version: '2'

services:
  main_server:
    image: cognituz/main_server:development
    ports: ["80:80"]
    volumes:
      - ui_assets:/static_assets/ui
      - api_assets:/static_assets/api
      - socks:/tmp/socks
    environment:
      API_SOCK_PATH: /tmp/socks/api.sock
      API_ASSETS_DIR: /static_assets/api
      UI_ASSETS_DIR: /static_assets/ui

  api:
    image: cognituz/api:development
    depends_on: [redis]
    links: [redis]
    env_file: ./default/rails.env
    volumes:
      - api_assets:/source/public
      - socks:/tmp/socks

  worker:
    image: cognituz/api:development
    depends_on: [redis]
    links: [redis]
    command: ./scripts/run_sidekiq.sh
    env_file: ./default/rails.env
    volumes:
      - api_assets:/source/public

  ui:
    image: cognituz/front:development
    env_file: ./default/front.env
    volumes:
      - ui_assets:/source/public

  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: on-failure:3

volumes:
  postgres_data:
  api_assets:
  ui_assets:
  socks:
