version: '2'

services:
  main_server:
    image: cognituz/main_server:development
    ports: ["80:80", "443:443"]
    depends_on: [api, certbot]
    volumes:
      - nginx_socks:/tmp/socks
      - acme_challenge:/var/www/acme_challenge
      - ssl_certs:/var/certs

      - ui_assets:/static_assets/ui
      - api_assets:/static_assets/api
      - socks:/tmp/socks
    environment:
      API_SOCK_PATH: /tmp/socks/api.sock
      API_ASSETS_DIR: /static_assets/api
      UI_ASSETS_DIR: /static_assets/ui

  api:
    image: cognituz/api:development
    depends_on: [redis]
    links: [redis]
    env_file: ./default/rails.env
    volumes:
      - api_assets:/source/public
      - socks:/tmp/socks

  worker:
    image: cognituz/api:development
    depends_on: [redis]
    links: [redis]
    command: ./scripts/run_sidekiq.sh
    env_file: ./default/rails.env
    volumes:
      - api_assets:/source/public

  ui:
    image: cognituz/front:development
    env_file: ./default/front.env
    volumes:
      - ui_assets:/source/public

  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: on-failure:3

  # Certbot renews SSL certificates periodically
  certbot:
    image: yavende/certbot:v1.0.0
    environment:
      - WEBROOT_PATH=/var/www/acme_challenge
      - SIGNING_EMAIL=info@cognituz.com
      - CERTS_PATH=/var/certs
    volumes:
      - acme_challenge:/var/www/acme_challenge
      - ssl_certs:/var/certs
      - certbot_data:/etc/letsencrypt

volumes:
  acme_challenge:
  certbot_data:
  ssl_certs:
  postgres_data:
  api_assets:
  ui_assets:
  socks:
